import { writeFileSync } from "node:fs"
import { createRequire } from "node:module"
import { dirname, resolve } from "node:path"
import ts from "typescript-api"

import { getConditions, scopes } from "./style-props-config"

export function generateStyleProps() {
  const require = createRequire(import.meta.url)
  const filename = resolve(
    dirname(require.resolve("@types/react/package.json")),
    "index.d.ts",
  )
  const program = ts.createProgram([filename], { skipLibCheck: true })
  const checker = program.getTypeChecker()
  const source = program.getSourceFile(filename)
  if (!source) throw new Error("React CSS property types not found")
  let properties: string[] = []
  function visit(node: ts.Node) {
    if (ts.isInterfaceDeclaration(node) && node.name.text === "CSSProperties") {
      properties = checker
        .getPropertiesOfType(checker.getTypeAtLocation(node))
        .map((property) => property.name)
        .sort()
    }
    ts.forEachChild(node, visit)
  }
  visit(source)
  if (properties.length < 300) throw new Error("Incomplete CSS property list")
  function spacingResets(property: string) {
    const match = /^(padding|margin)(Block|Inline)?$/.exec(property)
    if (!match) return ""
    const suffixes = match[2]
      ? [`${match[2]}Start`, `${match[2]}End`]
      : [
          "Top",
          "Right",
          "Bottom",
          "Left",
          "Block",
          "BlockStart",
          "BlockEnd",
          "Inline",
          "InlineStart",
          "InlineEnd",
        ]
    // StyleX gives longhands higher CSS priority than shorthands. Explicit nulls
    // remove earlier component classes without parsing raw CSS shorthand values.
    return suffixes.map((suffix) => `${match[1]}${suffix}: null, `).join("")
  }
  const declarations: string[] = []
  for (const property of properties) {
    declarations.push(
      `${property}: (value: string | number) => ({ ${spacingResets(property)}${property}: value }),`,
    )
  }
  const scopedDeclarations: string[] = []
  for (const [scope, selector] of Object.entries(scopes)) {
    for (const property of properties) {
      const variable = `--ysp-${scope}-${property}`
      scopedDeclarations.push(
        `${JSON.stringify(`${scope}_${property}`)}: { ${JSON.stringify(selector)}: { ${spacingResets(property)}${property}: ${JSON.stringify(`var(${variable})`)} } },`,
      )
    }
  }
  for (const [name, property] of [
    ["spaceX", "marginInlineStart"],
    ["spaceY", "marginBlockStart"],
  ]) {
    const variable = `--ysp-${name}`
    declarations.push(
      `${name}: (value: string | number) => ({ ${JSON.stringify(variable)}: value, ":where(*) > :not([hidden]) ~ :not([hidden])": { ${property}: ${JSON.stringify(`var(${variable})`)} } }),`,
    )
  }
  const gates = Object.entries(getConditions()).map(
    ([name, condition]) =>
      `${JSON.stringify(name)}: { ${JSON.stringify(`--ysp-${name}`)}: { default: "initial", ${JSON.stringify(condition)}: "var(--ysp-empty,)" } },`,
  )
  return `// Generated by style-props-generate.ts. Do not edit.\nimport type { StyleXStyle } from "./stylex"\nimport * as stylex from "@stylexjs/stylex"\n\ntype DynamicStyle = (value: string | number) => StyleXStyle\n\nexport const propertyStyles: Record<${[...properties, "spaceX", "spaceY"].map((name) => JSON.stringify(name)).join(" | ")}, DynamicStyle> = stylex.create({\n${declarations.join("\n")}\n})\n\nexport const scopedPropertyStyles: Record<string, StyleXStyle> = stylex.create({\n${scopedDeclarations.join("\n")}\n})\n\nexport const conditionStyles = stylex.create({\n${gates.join("\n")}\n})\n\nexport const variableStyles = stylex.create({ carrier: (value: string) => ({ "--ysp-carrier": value }) })\n`
}

if (import.meta.main) {
  writeFileSync(
    new URL("./style-props-styles.ts", import.meta.url),
    generateStyleProps(),
  )
}
