import type { SourceItem } from "@registry/items/types"

interface Definition {
  api: string[]
  categories: string[]
  description: string
  name: string
  registryDependencies?: string[]
  title: string
}

const definitions: Definition[] = [
  {
    api: ["Checkmark"],
    categories: ["display"],
    description: "Decorative check icon for a confirmed state.",
    name: "checkmark",
    title: "Checkmark",
  },
  {
    api: ["ClipboardProps", "Clipboard"],
    categories: ["controls"],
    description: "Copy text with accessible success and failure feedback.",
    name: "clipboard",
    title: "Clipboard",
  },
  {
    api: ["MarqueeProps", "Marquee"],
    categories: ["display"],
    description: "Pauseable scrolling content with reduced-motion support.",
    name: "marquee",
    title: "Marquee",
  },
  {
    api: ["NativeSelectProps", "NativeSelect"],
    categories: ["controls"],
    description:
      "Styled native select with browser keyboard and form behavior.",
    name: "native-select",
    title: "NativeSelect",
  },
  {
    api: ["RatingProps", "Rating"],
    categories: ["controls"],
    description: "Accessible star rating backed by Base UI Radio Group.",
    name: "rating",
    title: "Rating",
  },
  {
    api: ["Stat", "StatLabel", "StatValue", "StatDescription"],
    categories: ["display"],
    description: "Semantic definition list for a labeled metric.",
    name: "stat",
    title: "Stat",
  },
  {
    api: ["Steps", "StepsItem"],
    categories: ["navigation"],
    description: "Ordered process steps with a current-step indicator.",
    name: "steps",
    title: "Steps",
  },
  {
    api: ["Alert", "AlertTitle", "AlertDescription", "AlertAction"],
    categories: ["feedback"],
    description: "Status message with semantic variants and optional action.",
    name: "alert",
    title: "Alert",
  },
  {
    api: ["Avatar", "AvatarImage", "AvatarFallback", "AvatarPrimitive"],
    categories: ["display"],
    description: "Image avatar with accessible fallback.",
    name: "avatar",
    title: "Avatar",
  },
  {
    api: ["badgeVariants", "Badge", "BadgeProps"],
    categories: ["display"],
    description: "Compact status and metadata label.",
    name: "badge",
    title: "Badge",
  },
  {
    api: [
      "Breadcrumb",
      "BreadcrumbList",
      "BreadcrumbItem",
      "BreadcrumbLink",
      "BreadcrumbPage",
      "BreadcrumbSeparator",
      "BreadcrumbEllipsis",
    ],
    categories: ["navigation"],
    description: "Accessible breadcrumb navigation trail.",
    name: "breadcrumb",
    title: "Breadcrumb",
  },
  {
    api: [
      "Card",
      "CardFrame",
      "CardFrameHeader",
      "CardFrameTitle",
      "CardFrameDescription",
      "CardFrameAction",
      "CardFrameFooter",
      "CardHeader",
      "CardTitle",
      "CardDescription",
      "CardAction",
      "CardPanel",
      "CardFooter",
      "CardContent",
    ],
    categories: ["layout"],
    description: "Composable content and frame surfaces.",
    name: "card",
    title: "Card",
  },
  {
    api: [
      "Empty",
      "EmptyHeader",
      "EmptyMedia",
      "EmptyTitle",
      "EmptyDescription",
      "EmptyContent",
    ],
    categories: ["feedback"],
    description: "Empty-state layout with media and actions.",
    name: "empty",
    title: "Empty",
  },
  {
    api: [
      "Frame",
      "FramePanel",
      "FrameHeader",
      "FrameTitle",
      "FrameDescription",
      "FrameFooter",
    ],
    categories: ["layout"],
    description: "Grouped inset panels and supporting content.",
    name: "frame",
    title: "Frame",
  },
  {
    api: [
      "groupVariants",
      "Group",
      "GroupText",
      "GroupSeparator",
      "groupItemStyles",
      "ButtonGroup",
      "ButtonGroupText",
      "ButtonGroupSeparator",
    ],
    categories: ["layout"],
    description: "Visually joined controls and labels.",
    name: "group",
    registryDependencies: ["separator"],
    title: "Group",
  },
  {
    api: ["Kbd", "KbdGroup"],
    categories: ["display"],
    description: "Keyboard shortcut and key sequence display.",
    name: "kbd",
    title: "Kbd",
  },
  {
    api: ["Separator", "SeparatorPrimitive"],
    categories: ["layout"],
    description: "Accessible horizontal or vertical separator.",
    name: "separator",
    title: "Separator",
  },
  {
    api: ["Skeleton"],
    categories: ["feedback"],
    description: "Animated loading placeholder.",
    name: "skeleton",
    title: "Skeleton",
  },
  {
    api: [
      "Table",
      "TableHeader",
      "TableBody",
      "TableFooter",
      "TableRow",
      "TableHead",
      "TableCell",
      "TableCaption",
      "TableVariant",
      "TableProps",
    ],
    categories: ["display"],
    description: "Responsive semantic table with card presentation.",
    name: "table",
    title: "Table",
  },
  {
    api: ["Input", "InputProps", "InputPrimitive"],
    categories: ["forms"],
    description: "Styled text input with native and Base UI modes.",
    name: "input",
    title: "Input",
  },
  {
    api: ["Textarea", "TextareaProps", "FieldPrimitive"],
    categories: ["forms"],
    description: "Auto-sizing multiline text control.",
    name: "textarea",
    title: "Textarea",
  },
  {
    api: ["Label"],
    categories: ["forms"],
    description: "Composable form label.",
    name: "label",
    title: "Label",
  },
  {
    api: [
      "Field",
      "FieldLabel",
      "FieldItem",
      "FieldDescription",
      "FieldError",
      "FieldControl",
      "FieldValidity",
      "FieldPrimitive",
    ],
    categories: ["forms"],
    description: "Accessible form field composition and validation.",
    name: "field",
    title: "Field",
  },
  {
    api: ["Fieldset", "FieldsetLegend", "FieldsetPrimitive"],
    categories: ["forms"],
    description: "Accessible related-control grouping.",
    name: "fieldset",
    title: "Fieldset",
  },
  {
    api: ["Form", "FormPrimitive"],
    categories: ["forms"],
    description: "Base UI form root.",
    name: "form",
    title: "Form",
  },
  {
    api: [
      "InputGroup",
      "InputGroupAddon",
      "InputGroupText",
      "InputGroupInput",
      "InputGroupTextarea",
    ],
    categories: ["forms"],
    description: "Input composition with inline or block addons.",
    name: "input-group",
    registryDependencies: ["input", "textarea"],
    title: "Input Group",
  },
  {
    api: ["Checkbox", "CheckboxPrimitive"],
    categories: ["forms", "controls"],
    description: "Checkbox with checked and indeterminate states.",
    name: "checkbox",
    title: "Checkbox",
  },
  {
    api: ["CheckboxGroup", "CheckboxGroupPrimitive"],
    categories: ["forms", "controls"],
    description: "Accessible checkbox collection.",
    name: "checkbox-group",
    registryDependencies: ["checkbox"],
    title: "Checkbox Group",
  },
  {
    api: [
      "RadioGroup",
      "Radio",
      "RadioGroupPrimitive",
      "RadioPrimitive",
      "RadioGroupItem",
    ],
    categories: ["forms", "controls"],
    description: "Single-choice radio group.",
    name: "radio-group",
    title: "Radio Group",
  },
  {
    api: ["Switch", "SwitchPrimitive"],
    categories: ["forms", "controls"],
    description: "Binary switch control.",
    name: "switch",
    title: "Switch",
  },
  {
    api: ["Slider", "SliderValue", "SliderPrimitive"],
    categories: ["forms", "controls"],
    description: "Single or multi-thumb range input.",
    name: "slider",
    title: "Slider",
  },
  {
    api: [
      "Meter",
      "MeterLabel",
      "MeterTrack",
      "MeterIndicator",
      "MeterValue",
      "MeterPrimitive",
    ],
    categories: ["feedback"],
    description: "Scalar measurement within a known range.",
    name: "meter",
    title: "Meter",
  },
  {
    api: [
      "Progress",
      "ProgressLabel",
      "ProgressTrack",
      "ProgressIndicator",
      "ProgressValue",
      "ProgressPrimitive",
    ],
    categories: ["feedback"],
    description: "Task completion progress indicator.",
    name: "progress",
    title: "Progress",
  },
  {
    api: [
      "NumberField",
      "NumberFieldGroup",
      "NumberFieldDecrement",
      "NumberFieldIncrement",
      "NumberFieldInput",
      "NumberFieldScrubArea",
      "CursorGrowIcon",
      "NumberFieldContext",
      "NumberFieldPrimitive",
    ],
    categories: ["forms", "controls"],
    description: "Numeric input with steppers and scrub interaction.",
    name: "number-field",
    registryDependencies: ["label"],
    title: "Number Field",
  },
  {
    api: [
      "OTPField",
      "OTPFieldInput",
      "OTPFieldSeparator",
      "OTPFieldPrimitive",
    ],
    categories: ["forms", "controls"],
    description: "One-time-password segmented input.",
    name: "otp-field",
    registryDependencies: ["separator"],
    title: "OTP Field",
  },
  {
    api: ["toggleVariants", "Toggle", "ToggleVariantProps", "TogglePrimitive"],
    categories: ["controls"],
    description: "Two-state pressed control with variants.",
    name: "toggle",
    title: "Toggle",
  },
  {
    api: [
      "ToggleGroup",
      "ToggleGroupItem",
      "ToggleGroupSeparator",
      "ToggleGroupContext",
      "ToggleGroupPrimitive",
    ],
    categories: ["controls"],
    description: "Single or multiple selection toggle group.",
    name: "toggle-group",
    registryDependencies: ["separator", "toggle"],
    title: "Toggle Group",
  },
  {
    api: [
      "Toolbar",
      "ToolbarButton",
      "ToolbarLink",
      "ToolbarInput",
      "ToolbarGroup",
      "ToolbarSeparator",
      "ToolbarPrimitive",
    ],
    categories: ["controls"],
    description: "Accessible grouped command toolbar.",
    name: "toolbar",
    title: "Toolbar",
  },
]

const baseUiComponents = new Set([
  "avatar",
  "badge",
  "rating",
  "breadcrumb",
  "card",
  "checkbox",
  "checkbox-group",
  "field",
  "fieldset",
  "form",
  "group",
  "input",
  "label",
  "meter",
  "number-field",
  "otp-field",
  "progress",
  "radio-group",
  "separator",
  "slider",
  "switch",
  "table",
  "textarea",
  "toggle",
  "toggle-group",
  "toolbar",
])

const lucideComponents = new Set([
  "breadcrumb",
  "checkmark",
  "number-field",
  "rating",
])

export const displayFormItems: SourceItem[] = definitions.map(
  ({
    api,
    categories,
    description,
    name,
    registryDependencies = [],
    title,
  }) => ({
    categories,
    dependencies: [
      ...(baseUiComponents.has(name) ? ["@base-ui/react@^1.7.0"] : []),
      ...(lucideComponents.has(name) ? ["lucide-react@^1.33.0"] : []),
    ],
    description,
    devDependencies: [],
    docs: { api, usage: `Import from \`@/components/ui/${name}\`.` },
    files: [
      {
        path: `components/ui/${name}.tsx`,
        target: `@/components/ui/${name}.tsx`,
        type: "registry:ui" as const,
      },
    ],
    name,
    peerDependencies: ["react@>=18 <20", "react-dom@>=18 <20"],
    registryDependencies: [
      "base",
      ...registryDependencies,
      ...(["clipboard", "marquee", "rating"].includes(name)
        ? ["use-event-callback"]
        : []),
    ],
    title,
    type: "registry:ui" as const,
  }),
)
