import type { SourceItem } from "@registry/items/types"

export const foundationItems: SourceItem[] = [
  {
    categories: ["foundation"],
    dependencies: ["@stylexjs/stylex@^0.19.0", "clsx@^2.1.1"],
    description:
      "Native StyleX tokens, themes, reset, and typed component style props for Yopem UI.",
    devDependencies: [],
    docs: {
      api: [
        "lightValues",
        "darkValues",
        "tokens",
        "themeMarker",
        "lightTheme",
        "darkTheme",
        "rootStyles",
        "stylexProps",
        "mergeStyleProps",
        "StyleXStyle",
        "StyleXProps",
        "StyleProps",
        "StyleObject",
        "ResponsiveValue",
        "StyleComponentProps",
        "splitStyleProps",
        "resolveStyleProps",
        "normalizeStyleProps",
        "isStyleProp",
        "Breakpoint",
        "Condition",
        "ResponsiveCondition",
        "aliases",
        "breakpoints",
        "getConditions",
        "mediaConditions",
        "scopes",
        "selectors",
        "conditionStyles",
        "propertyStyles",
        "scopedPropertyStyles",
        "variableStyles",
      ],
      usage:
        "Copy the base files, configure StyleX and import styles.css. Native tokens provide light defaults without a provider or script. Add the optional theme item for light/dark/system switching. Customize in the copied tokens.stylex.ts with stylex.createTheme(tokens, { ...lightValues, '--primary': '...' }); for dark use ...darkValues, not a partial theme layered over darkTheme. Keep these spreads in tokens.stylex.ts: StyleX 0.19 does not expand imported constant objects.",
    },
    files: [
      {
        path: "styles/tokens.stylex.ts",
        target: "@/styles/tokens.stylex.ts",
        type: "registry:style",
      },
      {
        path: "styles/styles.css",
        target: "@/styles/styles.css",
        type: "registry:style",
      },
      {
        path: "lib/stylex.ts",
        target: "@/lib/stylex.ts",
        type: "registry:lib",
      },
      {
        path: "lib/style-props.ts",
        target: "@/lib/style-props.ts",
        type: "registry:lib",
      },
      {
        path: "lib/style-props-config.ts",
        target: "@/lib/style-props-config.ts",
        type: "registry:lib",
      },
      {
        path: "lib/style-props-styles.ts",
        target: "@/lib/style-props-styles.ts",
        type: "registry:lib",
      },
    ],
    name: "base",
    peerDependencies: ["react@>=18 <20", "react-dom@>=18 <20"],
    registryDependencies: [],
    title: "Yopem base",
    type: "registry:base",
  },
  {
    categories: ["foundation"],
    dependencies: [],
    description:
      "Optional light, dark and system theme runtime with a CSP-compatible initial-paint script.",
    devDependencies: [],
    docs: {
      api: [
        "createThemeConfig",
        "getRootThemeProps",
        "ThemeScript",
        "Theme",
        "ResolvedTheme",
        "STORAGE_KEY",
        "MEDIA_QUERY",
        "themeConfig",
        "ThemeConfig",
        "themeClasses",
        "themeClassNames",
        "ThemeScriptProps",
        "ThemeProvider",
        "useTheme",
        "ThemeProviderProps",
      ],
      usage:
        "Create complete light/dark themes in tokens.stylex.ts with StyleX, export those themes, then call createThemeConfig({ light, dark }) in your existing server-safe root layout. Pass the same serializable themes config to getRootThemeProps('light', themes), ThemeScript and ThemeProvider. Match defaultTheme and storageKey between script and provider. Pass your CSP nonce to ThemeScript; suppress hydration warnings on html because the script changes its class and data-theme before hydration. theme.tsx is server-safe; only theme-provider.tsx is a client entry.",
    },
    files: [
      {
        path: "theme/theme.tsx",
        target: "@/theme/theme.tsx",
        type: "registry:lib",
      },
      {
        path: "theme/theme-provider.tsx",
        target: "@/theme/theme-provider.tsx",
        type: "registry:lib",
      },
    ],
    name: "theme",
    peerDependencies: ["react@>=18 <20", "react-dom@>=18 <20"],
    registryDependencies: ["base"],
    title: "Theme runtime",
    type: "registry:lib",
  },
  {
    categories: ["feedback"],
    dependencies: ["lucide-react@^1.33.0"],
    description: "Accessible animated loading indicator.",
    devDependencies: [],
    docs: {
      api: ["Spinner"],
      usage: "`<Spinner />`",
    },
    files: [
      {
        path: "components/ui/spinner.tsx",
        target: "@/components/ui/spinner.tsx",
        type: "registry:ui",
      },
    ],
    name: "spinner",
    peerDependencies: ["react@>=18 <20"],
    registryDependencies: ["base"],
    title: "Spinner",
    type: "registry:ui",
  },
  {
    categories: ["actions"],
    dependencies: ["@base-ui/react@^1.7.0"],
    description:
      "Button with variants, sizes, rendering composition, and loading state.",
    devDependencies: [],
    docs: {
      api: ["buttonVariants", "Button", "ButtonProps"],
      usage: "`<Button>Save</Button>`",
    },
    files: [
      {
        path: "components/ui/button.tsx",
        target: "@/components/ui/button.tsx",
        type: "registry:ui",
      },
    ],
    name: "button",
    peerDependencies: ["react@>=18 <20"],
    registryDependencies: ["base", "spinner"],
    title: "Button",
    type: "registry:ui",
  },
]
