import type { SourceItem } from "@registry/items/types"

interface Definition {
  api: string[]
  categories: string[]
  description: string
  name: string
  registryDependencies?: string[]
  title: string
}

const definitions: Definition[] = [
  {
    api: [
      "Accordion",
      "AccordionItem",
      "AccordionTrigger",
      "AccordionPanel",
      "AccordionPrimitive",
      "AccordionContent",
    ],
    categories: ["disclosure"],
    description: "Arranges disclosure sections vertically.",
    name: "accordion",
    title: "Accordion",
  },
  {
    api: [
      "Collapsible",
      "CollapsibleTrigger",
      "CollapsiblePanel",
      "CollapsiblePrimitive",
      "CollapsibleContent",
    ],
    categories: ["disclosure"],
    description: "Provides a content region that expands and collapses.",
    name: "collapsible",
    title: "Collapsible",
  },
  {
    api: [
      "Tabs",
      "TabsList",
      "TabsTab",
      "TabsPanel",
      "tabsSlotStyles",
      "TabsPrimitive",
      "TabsTrigger",
      "TabsContent",
      "TabsSize",
      "TabsVariant",
    ],
    categories: ["navigation"],
    description: "Displays tabbed content with default and underline variants.",
    name: "tabs",
    title: "Tabs",
  },
  {
    api: [
      "Pagination",
      "PaginationContent",
      "PaginationItem",
      "PaginationLink",
      "PaginationPrevious",
      "PaginationNext",
      "PaginationEllipsis",
      "PaginationLinkProps",
    ],
    categories: ["navigation"],
    description: "Provides accessible page navigation controls.",
    name: "pagination",
    registryDependencies: ["button"],
    title: "Pagination",
  },
  {
    api: ["ScrollArea", "ScrollBar", "ScrollAreaPrimitive"],
    categories: ["layout"],
    description:
      "Provides custom scrollbars, edge fades, and overflow containment.",
    name: "scroll-area",
    title: "Scroll Area",
  },
  {
    api: [
      "AlertDialogTrigger",
      "AlertDialogBackdrop",
      "AlertDialogViewport",
      "AlertDialogPopup",
      "AlertDialogHeader",
      "AlertDialogFooter",
      "AlertDialogTitle",
      "AlertDialogDescription",
      "AlertDialogClose",
      "AlertDialogCreateHandle",
      "AlertDialog",
      "AlertDialogPortal",
      "AlertDialogPrimitive",
      "AlertDialogOverlay",
      "AlertDialogContent",
    ],
    categories: ["overlays"],
    description:
      "Provides a modal confirmation dialog for destructive or important actions.",
    name: "alert-dialog",
    title: "Alert Dialog",
  },
  {
    api: [
      "ContextMenuTrigger",
      "ContextMenuPopup",
      "ContextMenuGroup",
      "ContextMenuItem",
      "ContextMenuLinkItem",
      "ContextMenuCheckboxItem",
      "ContextMenuRadioGroup",
      "ContextMenuRadioItem",
      "ContextMenuGroupLabel",
      "ContextMenuSeparator",
      "ContextMenuShortcut",
      "ContextMenuSub",
      "ContextMenuSubTrigger",
      "ContextMenuSubPopup",
      "contextMenuSlotStyles",
      "ContextMenu",
      "ContextMenuPortal",
      "ContextMenuPrimitive",
    ],
    categories: ["overlays", "navigation"],
    description: "Shows a context menu at the pointer position.",
    name: "context-menu",
    title: "Context Menu",
  },
  {
    api: [
      "DialogTrigger",
      "DialogClose",
      "DialogBackdrop",
      "DialogViewport",
      "DialogPopup",
      "DialogHeader",
      "DialogFooter",
      "DialogTitle",
      "DialogDescription",
      "DialogPanel",
      "DialogCreateHandle",
      "Dialog",
      "DialogPortal",
      "DialogPrimitive",
      "DialogOverlay",
      "DialogContent",
    ],
    categories: ["overlays"],
    description:
      "Provides a modal dialog with an optional scrolling panel and mobile layout.",
    name: "dialog",
    registryDependencies: ["button", "scroll-area"],
    title: "Dialog",
  },
  {
    api: [
      "Drawer",
      "DrawerTrigger",
      "DrawerClose",
      "DrawerSwipeArea",
      "DrawerBackdrop",
      "DrawerViewport",
      "DrawerPopup",
      "DrawerHeader",
      "DrawerFooter",
      "DrawerTitle",
      "DrawerDescription",
      "DrawerPanel",
      "DrawerBar",
      "DrawerMenu",
      "DrawerMenuItem",
      "DrawerMenuSeparator",
      "DrawerMenuGroup",
      "DrawerMenuGroupLabel",
      "DrawerMenuTrigger",
      "DrawerMenuCheckboxItem",
      "DrawerMenuRadioGroup",
      "DrawerMenuRadioItem",
      "drawerSlotStyles",
      "DrawerCreateHandle",
      "DrawerPortal",
      "DrawerContent",
      "DrawerPrimitive",
    ],
    categories: ["overlays"],
    description:
      "Provides an edge drawer with swipe gestures, stacking, and menu composition.",
    name: "drawer",
    registryDependencies: ["button", "scroll-area"],
    title: "Drawer",
  },
  {
    api: [
      "MenuTrigger",
      "MenuPopup",
      "MenuGroup",
      "MenuItem",
      "MenuLinkItem",
      "MenuCheckboxItem",
      "MenuRadioGroup",
      "MenuRadioItem",
      "MenuGroupLabel",
      "MenuSeparator",
      "MenuShortcut",
      "MenuSub",
      "MenuSubTrigger",
      "MenuSubPopup",
      "menuSlotStyles",
      "MenuCreateHandle",
      "Menu",
      "MenuPortal",
      "MenuPrimitive",
      "DropdownMenuCreateHandle",
      "DropdownMenu",
      "DropdownMenuPortal",
      "DropdownMenuTrigger",
      "DropdownMenuContent",
      "DropdownMenuGroup",
      "DropdownMenuItem",
      "DropdownMenuCheckboxItem",
      "DropdownMenuRadioGroup",
      "DropdownMenuRadioItem",
      "DropdownMenuLabel",
      "DropdownMenuSeparator",
      "DropdownMenuShortcut",
      "DropdownMenuSub",
      "DropdownMenuSubTrigger",
      "DropdownMenuSubContent",
    ],
    categories: ["overlays", "navigation"],
    description: "Provides an action menu with links, choices, and submenus.",
    name: "menu",
    title: "Menu",
  },
  {
    api: [
      "PopoverTrigger",
      "PopoverPopup",
      "PopoverClose",
      "PopoverTitle",
      "PopoverDescription",
      "PopoverCreateHandle",
      "Popover",
      "PopoverPrimitive",
      "PopoverContent",
    ],
    categories: ["overlays"],
    description:
      "Shows an anchored popup with transitions that adapt to the viewport.",
    name: "popover",
    title: "Popover",
  },
  {
    api: [
      "PreviewCardTrigger",
      "PreviewCardPopup",
      "PreviewCard",
      "PreviewCardPrimitive",
      "HoverCard",
      "HoverCardTrigger",
      "HoverCardContent",
    ],
    categories: ["overlays"],
    description: "Shows a preview card for pointer and keyboard interaction.",
    name: "preview-card",
    title: "Preview Card",
  },
  {
    api: [
      "selectTriggerVariants",
      "SelectButton",
      "SelectTrigger",
      "SelectValue",
      "SelectPopup",
      "SelectItem",
      "SelectSeparator",
      "SelectGroup",
      "SelectLabel",
      "SelectGroupLabel",
      "selectSlotStyles",
      "Select",
      "selectTriggerIconClassName",
      "SelectButtonProps",
      "SelectPrimitive",
      "SelectContent",
    ],
    categories: ["forms", "controls"],
    description: "Provides a popup for single or multiple value selection.",
    name: "select",
    title: "Select",
  },
  {
    api: [
      "SheetTrigger",
      "SheetClose",
      "SheetBackdrop",
      "SheetViewport",
      "SheetPopup",
      "SheetHeader",
      "SheetFooter",
      "SheetTitle",
      "SheetDescription",
      "SheetPanel",
      "Sheet",
      "SheetPortal",
      "SheetPrimitive",
      "SheetOverlay",
      "SheetContent",
    ],
    categories: ["overlays"],
    description: "Shows a modal panel at a viewport edge.",
    name: "sheet",
    registryDependencies: ["button", "scroll-area"],
    title: "Sheet",
  },
  {
    api: [
      "TooltipTrigger",
      "TooltipPopup",
      "TooltipCreateHandle",
      "TooltipProvider",
      "Tooltip",
      "TooltipPrimitive",
      "TooltipContent",
    ],
    categories: ["overlays"],
    description: "Shows an accessible description popup at an anchor.",
    name: "tooltip",
    title: "Tooltip",
  },
  {
    api: [
      "AutocompletePopup",
      "AutocompleteItem",
      "AutocompleteSeparator",
      "AutocompleteGroup",
      "AutocompleteGroupLabel",
      "AutocompleteEmpty",
      "AutocompleteRow",
      "AutocompleteList",
      "AutocompleteClear",
      "AutocompleteStatus",
      "AutocompleteTrigger",
      "autocompleteSlotStyles",
      "Autocomplete",
      "AutocompleteInput",
      "AutocompleteValue",
      "AutocompleteCollection",
      "useAutocompleteFilter",
      "AutocompletePrimitive",
    ],
    categories: ["forms", "controls"],
    description:
      "Provides text suggestions with filtering and grouped results.",
    name: "autocomplete",
    registryDependencies: ["input", "scroll-area"],
    title: "Autocomplete",
  },
  {
    api: ["Calendar"],
    categories: ["forms", "date-time"],
    description:
      "Provides a calendar for single, multiple, and range date selection.",
    name: "calendar",
    title: "Calendar",
  },
  {
    api: [
      "Combobox",
      "ComboboxTrigger",
      "ComboboxPopup",
      "ComboboxItem",
      "ComboboxSeparator",
      "ComboboxGroup",
      "ComboboxGroupLabel",
      "ComboboxEmpty",
      "ComboboxRow",
      "ComboboxList",
      "ComboboxClear",
      "ComboboxStatus",
      "ComboboxChips",
      "ComboboxChip",
      "ComboboxChipRemove",
      "comboboxSlotStyles",
      "ComboboxContext",
      "ComboboxChipsInput",
      "ComboboxInput",
      "ComboboxValue",
      "ComboboxCollection",
      "useComboboxFilter",
      "ComboboxPrimitive",
    ],
    categories: ["forms", "controls"],
    description:
      "Provides a searchable control for single or multiple selection.",
    name: "combobox",
    registryDependencies: ["input", "scroll-area"],
    title: "Combobox",
  },
  {
    api: [
      "CommandDialogTrigger",
      "CommandDialogBackdrop",
      "CommandDialogViewport",
      "CommandDialogPopup",
      "Command",
      "CommandInput",
      "CommandList",
      "CommandEmpty",
      "CommandPanel",
      "CommandGroup",
      "CommandGroupLabel",
      "CommandItem",
      "CommandSeparator",
      "CommandShortcut",
      "CommandFooter",
      "CommandDialog",
      "CommandDialogPortal",
      "CommandCreateHandle",
      "CommandCollection",
      "CommandDialogPrimitive",
    ],
    categories: ["navigation", "controls"],
    description: "Provides a command palette and searchable action list.",
    name: "command",
    registryDependencies: ["autocomplete"],
    title: "Command",
  },
  {
    api: [
      "useSidebar",
      "SidebarProvider",
      "Sidebar",
      "SidebarTrigger",
      "SidebarRail",
      "SidebarInset",
      "SidebarInput",
      "SidebarHeader",
      "SidebarFooter",
      "SidebarSeparator",
      "SidebarContent",
      "SidebarGroup",
      "SidebarGroupLabel",
      "SidebarGroupAction",
      "SidebarGroupContent",
      "SidebarMenu",
      "SidebarMenuItem",
      "SidebarMenuButton",
      "SidebarMenuAction",
      "SidebarMenuBadge",
      "SidebarMenuSkeleton",
      "SidebarMenuSub",
      "SidebarMenuSubItem",
      "SidebarMenuSubButton",
      "SidebarMenuText",
      "sidebarSlotStyles",
      "SidebarContextProps",
      "SidebarContext",
    ],
    categories: ["navigation", "layout"],
    description: "Provides a responsive application sidebar that collapses.",
    name: "sidebar",
    registryDependencies: [
      "button",
      "input",
      "scroll-area",
      "separator",
      "sheet",
      "skeleton",
      "tooltip",
    ],
    title: "Sidebar",
  },
  {
    api: [
      "ToastProvider",
      "AnchoredToastProvider",
      "toastManager",
      "anchoredToastManager",
      "ToastPosition",
      "ToastProviderProps",
      "AnchoredToastProviderProps",
      "ToastPrimitive",
    ],
    categories: ["feedback", "overlays"],
    description: "Displays stacked and anchored toast notifications.",
    name: "toast",
    registryDependencies: ["button"],
    title: "Toast",
  },
]

const lucideComponents = new Set([
  "accordion",
  "autocomplete",
  "calendar",
  "combobox",
  "command",
  "context-menu",
  "dialog",
  "drawer",
  "menu",
  "pagination",
  "select",
  "sheet",
  "sidebar",
  "toast",
])

export const remainingItems: SourceItem[] = definitions.map(
  ({
    api,
    categories,
    description,
    name,
    registryDependencies = [],
    title,
  }) => ({
    categories,
    dependencies: [
      ...(name === "calendar"
        ? ["@daypicker/react@^10.0.1"]
        : ["@base-ui/react@^1.7.0"]),
      ...(lucideComponents.has(name) ? ["lucide-react@^1.33.0"] : []),
    ],
    description,
    devDependencies: [],
    docs: { api, usage: `Import from \`@/components/ui/${name}\`.` },
    files: [
      {
        path: `components/ui/${name}.tsx`,
        target: `@/components/ui/${name}.tsx`,
        type: "registry:ui" as const,
      },
    ],
    name,
    peerDependencies: ["react@>=18 <20", "react-dom@>=18 <20"],
    registryDependencies: [
      "base",
      ...registryDependencies,
      ...(name === "sidebar" ? ["use-event-callback"] : []),
    ],
    title,
    type: "registry:ui" as const,
  }),
)
