import { tokens } from "@registry/styles/tokens.stylex"
import * as stylex from "@stylexjs/stylex"

export const docsStyles = stylex.create({
  h2: {
    fontFamily: tokens.fontHeading,
    fontSize: "1.5rem",
    fontWeight: 650,
    letterSpacing: "-0.025em",
    lineHeight: 1.3,
    marginBlockStart: "3rem",
    marginBlockEnd: "1rem",
    scrollMarginBlockStart: "6rem",
  },
  h3: {
    fontFamily: tokens.fontHeading,
    fontSize: "1.2rem",
    fontWeight: 600,
    lineHeight: 1.4,
    marginBlockStart: "2rem",
    marginBlockEnd: "0.75rem",
    scrollMarginBlockStart: "6rem",
  },
  h4: {
    fontSize: "1rem",
    fontWeight: 600,
    marginBlockStart: "1.5rem",
    marginBlockEnd: "0.5rem",
    scrollMarginBlockStart: "6rem",
  },
  p: { marginBlock: "1rem", lineHeight: 1.8 },
  ul: {
    listStyleType: "disc",
    paddingInlineStart: "1.5rem",
    marginBlock: "1rem",
  },
  ol: {
    listStyleType: "decimal",
    paddingInlineStart: "1.5rem",
    marginBlock: "1rem",
  },
  li: {
    paddingInlineStart: "0.25rem",
    marginBlock: "0.5rem",
    lineHeight: 1.75,
  },
  inlineCode: {
    fontFamily: tokens.fontMono,
    fontSize: "0.875em",
    backgroundColor: tokens.code,
    color: tokens.codeForeground,
    borderRadius: tokens.radiusSmall,
    paddingBlock: "0.15rem",
    paddingInline: "0.35rem",
    overflowWrap: "anywhere",
  },
  details: {
    borderColor: tokens.border,
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: tokens.radiusLarge,
    padding: "1rem",
    marginBlock: "1rem",
  },
  summary: {
    cursor: "pointer",
    fontWeight: 600,
    borderRadius: tokens.radiusSmall,
    ":focus-visible": { outline: `2px solid ${tokens.ring}`, outlineOffset: 4 },
  },
  tableWrapper: {
    overflowX: "auto",
    marginBlock: "1.5rem",
    borderColor: tokens.border,
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: tokens.radiusLarge,
  },
  table: {
    inlineSize: "100%",
    borderCollapse: "collapse",
    fontSize: "0.875rem",
    lineHeight: 1.6,
  },
  th: {
    textAlign: "start",
    fontWeight: 600,
    padding: "0.875rem",
    backgroundColor: tokens.muted,
    borderBlockEnd: `1px solid ${tokens.border}`,
  },
  td: {
    textAlign: "start",
    padding: "0.875rem",
    verticalAlign: "top",
    borderBlockEnd: `1px solid ${tokens.border}`,
  },
  link: {
    color: tokens.foreground,
    textDecoration: "underline",
    textDecorationColor: tokens.border,
    textUnderlineOffset: "0.25em",
    borderRadius: tokens.radiusSmall,
    ":hover": { textDecorationColor: tokens.foreground },
    ":focus-visible": { outline: `2px solid ${tokens.ring}`, outlineOffset: 4 },
  },
  preview: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: "1rem",
    minBlockSize: "14rem",
    padding: { default: "2.5rem", "@media (max-width: 639px)": "1.25rem" },
    borderColor: tokens.border,
    borderStyle: "solid",
    borderWidth: 1,
    borderRadius: tokens.radiusLarge,
    backgroundColor: tokens.background,
    marginBlock: "1.5rem",
  },
  links: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "1rem",
    marginBlock: "1.5rem",
  },
  section: { marginBlock: "2rem", minInlineSize: 0 },
  muted: { color: tokens.mutedForeground },
  strong: { fontWeight: 600, color: tokens.foreground },
  pre: {
    backgroundColor: tokens.code,
    color: tokens.codeForeground,
    padding: "1.25rem",
    borderRadius: tokens.radiusLarge,
    overflowX: "auto",
    fontFamily: tokens.fontMono,
    fontSize: "0.8125rem",
    lineHeight: 1.75,
    marginBlock: "1.5rem",
  },
  code: { fontFamily: tokens.fontMono, fontSize: "0.875em" },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 16rem), 1fr))",
    gap: "1rem",
    marginBlock: "1.5rem",
  },
  card: {
    display: "block",
    padding: "1.5rem",
    borderRadius: tokens.radiusLarge,
    borderColor: tokens.border,
    borderStyle: "solid",
    borderWidth: 1,
    backgroundColor: tokens.card,
    color: tokens.cardForeground,
    textDecoration: "none",
    ":hover": { backgroundColor: tokens.accent },
    ":focus-visible": { outline: `2px solid ${tokens.ring}`, outlineOffset: 4 },
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    paddingBlock: "0.2rem",
    paddingInline: "0.5rem",
    borderRadius: tokens.radiusSmall,
    backgroundColor: tokens.secondary,
    color: tokens.secondaryForeground,
    fontSize: "0.75rem",
    fontWeight: 500,
  },
})
