/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StylexIndexRouteImport } from './routes/stylex/index'
import { Route as TailwindIndexRouteImport } from './routes/tailwind/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StylexIndexRoute = StylexIndexRouteImport.update({
  id: '/stylex/',
  path: '/stylex/',
  getParentRoute: () => rootRouteImport,
} as any)
const TailwindIndexRoute = TailwindIndexRouteImport.update({
  id: '/tailwind/',
  path: '/tailwind/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stylex/': typeof StylexIndexRoute
  '/tailwind/': typeof TailwindIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stylex': typeof StylexIndexRoute
  '/tailwind': typeof TailwindIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stylex/': typeof StylexIndexRoute
  '/tailwind/': typeof TailwindIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stylex/' | '/tailwind/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stylex' | '/tailwind'
  id: '__root__' | '/' | '/stylex/' | '/tailwind/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StylexIndexRoute: typeof StylexIndexRoute
  TailwindIndexRoute: typeof TailwindIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylex/': {
      id: '/stylex/'
      path: '/stylex'
      fullPath: '/stylex/'
      preLoaderRoute: typeof StylexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailwind/': {
      id: '/tailwind/'
      path: '/tailwind'
      fullPath: '/tailwind/'
      preLoaderRoute: typeof TailwindIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StylexIndexRoute: StylexIndexRoute,
  TailwindIndexRoute: TailwindIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
