name: Publish preview packages

on: [push, pull_request]

permissions: {}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run:
          bun run pkg-pr-new publish --bun --previewVersion --packageManager=bun
          ./packages/cli ./packages/oxlint-plugin
